---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intro-graphql-ja
  name: intro-graphql-ja
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intro-graphql-ja
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: intro-graphql-ja
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: intro-graphql-ja
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: intro-graphql-ja
  name: intro-graphql-ja
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: intro-graphql-ja
  type: ClusterIP
