---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura-auth-slack-es
  name: hasura-auth-slack-es
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-auth-slack-es
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: hasura-auth-slack-es
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: hasura-auth-slack-es
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-auth-slack-es
  name: hasura-auth-slack-es
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-auth-slack-es
  type: ClusterIP
